# Generated by Django 3.2 on 2025-04-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
